# Generated by Django 4.1.2 on 2023-10-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=62, verbose_name='会社名')),
                ('job_name', models.CharField(max_length=62, verbose_name='求人名')),
                ('salary', models.CharField(max_length=62, verbose_name='給料')),
                ('job_content', models.TextField(verbose_name='仕事内容')),
                ('application_requirement', models.TextField(verbose_name='応募要件')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name_plural': '求人',
                'db_table': 'articles',
            },
        ),
    ]
